### ISSUE TITLE
arm64 releases

### ISSUE THREAD

**Issue by loralb** [thombles/hashgood#4]
Hello! Thank you for this program, much appreciated!
Would it be possible for you to also add arm64 binaries in the release page?

**Comment by thombles** [comment]
I'm guessing this request concerns Linux since the x86 emulation on Windows and Mac would presumably cover things fairly well. I had a look at the current state of GitHub Actions and unfortunately the Linux ARM images are [not yet available for regular users](https://github.com/actions/runner-images). They have [some beta images](https://github.com/actions/partner-runner-images) but these are only for customers paying for custom runners.

I'm afraid I'm not willing to bother with self-hosted runners or manually creating builds for hashgood, but I assume these images will become available for general use eventually and I'll leave this issue open as a reminder.

**Comment by thombles** [comment]
This is now resolved with the v0.5.0 release: https://octet-stream.net/p/hashgood/releases/v0.5.0.html

Contrary to my previous post, I am now bothering to self-host builders.

Note that I have moved this project away from GitHub and will archive the repo after closing this issue. Any further feedback will be appreciated via email. :)
